Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Splitting data into training and testing data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 100)
------------------


[0;31m[0m
[0;31mValueError[0mTraceback (most recent call last)
[0;32m<ipython-input-6-31cc3063e6da>[0m in [0;36m<cell line: 4>[0;34m()[0m
[1;32m      2[0m [0;32mfrom[0m [0msklearn[0m[0;34m.[0m[0mmodel_selection[0m [0;32mimport[0m [0mtrain_test_split[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;34m[0m[0m
[0;32m----> 4[0;31m [0mX_train[0m[0;34m,[0m [0mX_test[0m[0;34m,[0m [0my_train[0m[0;34m,[0m [0my_test[0m [0;34m=[0m [0mtrain_test_split[0m[0;34m([0m[0mX[0m[0;34m,[0m [0my[0m[0;34m,[0m [0mrandom_state[0m [0;34m=[0m [0;36m100[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py[0m in [0;36mtrain_test_split[0;34m(test_size, train_size, random_state, shuffle, stratify, *arrays)[0m
[1;32m   2560[0m [0;34m[0m[0m
[1;32m   2561[0m     [0mn_samples[0m [0;34m=[0m [0m_num_samples[0m[0;34m([0m[0marrays[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2562[0;31m     n_train, n_test = _validate_shuffle_split(
[0m[1;32m   2563[0m         [0mn_samples[0m[0;34m,[0m [0mtest_size[0m[0;34m,[0m [0mtrain_size[0m[0;34m,[0m [0mdefault_test_size[0m[0;34m=[0m[0;36m0.25[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2564[0m     )

[0;32m/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py[0m in [0;36m_validate_shuffle_split[0;34m(n_samples, test_size, train_size, default_test_size)[0m
[1;32m   2234[0m [0;34m[0m[0m
[1;32m   2235[0m     [0;32mif[0m [0mn_train[0m [0;34m==[0m [0;36m0[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 2236[0;31m         raise ValueError(
[0m[1;32m   2237[0m             [0;34m"With n_samples={}, test_size={} and train_size={}, the "[0m[0;34m[0m[0;34m[0m[0m
[1;32m   2238[0m             [0;34m"resulting train set will be empty. Adjust any of the "[0m[0;34m[0m[0;34m[0m[0m

[0;31mValueError[0m: With n_samples=0, test_size=0.25 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

